---
title: "Assignment 7"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 1 (7 points)

A student stated: "Adding predictor variables to a regression model can never reduce $R^2$, so we should include all available predictor variables in the model." Comment.

# Exercise 2 (7 points)

Why is it not meaningful to attach a sign to the coefficient of multiple correlation $R$, although we do so for the coefficient of simple correlation $r_{12}$?

# Exercise 3 (7 points)

In a small-scale regression study, the following data were obtained,

| Y    | $X_1$ | $X_2$ |
|------|-------|-------|
| 42.0 |   7.0 |  33.0 |
| 33.0 |   4.0 |  41.0 |
| 75.0 |  16.0 |   7.0 |
| 28.0 |   3.0 |  49.0 |
| 91.0 |  21.0 |   5.0 |
| 55.0 |   8.0 |  31.0 |

Assume the standard multiple regression model with independent normal error terms. Compute $\mathbf{b}$, $\mathbf{e}$, $\mathbf{H}$, SSErr,  $R^2$, $s^2_{\mathbf{b}}$, $\hat Y$ for $X_1 = 10$, $X_2 = 30$. You can do the computations using software or by hand, although it would be  lengthy to do them by hand.

# Exercise 4 (14 points)

The data set "Brand preference" is available [here](data/CH06PR05.txt).

It was collected to study thee relation between degree of brand liking (Y, first column) and moisture content ($X_1$, second column) and sweetness ($X_2$, third column) of the product.

a. Fit a regression model to these data and state the estimated regression function. Interpret $b_1$.
b. Obtain residual plots. What information do they provide? Plot residuals against fitted values, against each predictor, and against the product of predictors.
c. Test homoscedasticity.
d. Conduct a formal lack of fit test.
e. test whether the proposed linear regression model is significant. What do the results of the ANOVA F-test imply about the slopes?
f. Estimate both slopes simultaneously using the Bonferroni procedure with at least a 99 percent confidence level.
g. Report $R^2$ and adjusted $R^2$. How are they interpreted here?
h. Calculate the squared correlation coefficient between $Y_i$ and $\hat Y_i$. Compare with part g).
i. Obtain a 99% confidence interval for $E(Y)$ when $X_1 = 5$ and $X_2 = 4$. Interpret it.
j. obtain a 99% prediction interval for a new observation $Y$ when $X_1 = 5$ ane $X_2 =   4$.
